### ISSUE TITLE
Parsing BFL Files

### ISSUE THREAD

**Issue by baconninja87** [gimbal-ghost/gimbal-ghost#39]
Are there any plans to add the ability to parse BFL logs for use with Gimbal Ghost for those of us who have SD cards or other not on chip storage for the blackbox on our quads which doesn't result in BBL files?  I am able to export the CSV using blackbox tools manually, so I assume it is theoretically possible.  The header information and log end markers look to be exactly the same between the two formats.

**Comment by joshuadavidson** [comment]
Yeah this should be totally doable. Can you post a BFL file here (or a link to one) and I'll take a look?

**Comment by joshuadavidson** [comment]
@baconninja87 release v1.1.0 has gone out with support for `.bfl` files. It should be automatically downloaded when opening the app.

**Comment by baconninja87** [comment]
Sorry I didnt get your request for the file since apparently GitHub emails went to spam...but I just tested it and it works perfect!!  Thank you for the hard work man, and this was a way better experience than using other options for this overlay.  15 mins to render vs 30 seconds, hands down better.

**Comment by joshuadavidson** [comment]
@baconninja87 no worries man. Glad it's working for ya!
