### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by wetheredge** [gimbal-ghost/gimbal-ghost#46]
I've been working on getting this to work with my new blackbox parser library[^1] and have been running into some difficulties that I think are due to out-of-date dependencies. Would you consider enabling Dependabot or [Renovate](https://www.mend.io/renovate/)?

At the moment, both npm's `package-lock.json` and yarn's `yarn.lock` are in the repo. I'm not sure how Dependabot or Renovate would deal with that; maybe it would be good to only have files for one package manager. Personally, I like [pnpm](https://pnpm.io), but it's only supported by Renovate.

[^1]: https://github.com/blackbox-log/blackbox-log-js. The code is mostly done, but it still needs docs & to be published before it's ready.

**Comment by joshuadavidson** [comment]
Are you able to identify the libraries that are causing issues? Once identified we can go through and make a single update. I'm hesitant having deps updated automatically which would require testing each time something is updated to make sure it doesn't break for everyone. Thoughts?

**Comment by wetheredge** [comment]
I believe the only update that is *required* is TypeScript itself, [as noted here](https://blackbox-log.github.io/blackbox-log-ts/#md:installation). If you go to TS v5, that will also require updating Vue, vue-tsc, and probably vite.

**Comment by joshuadavidson** [comment]
Yikes that is quite a bit. I'd much rather open a new gimbal-ghost web repo and explore using your WASM library there. Thoughts?

**Comment by wetheredge** [comment]
I've realized that the version of TS recorded in your `package-log.json` is actually 4.7.4, so it is compatible with `blackbox-log` without any updates. You will need to either change to `"moduleResolution": "nodenext"` or add `"resolvePackageJsonExports": true` for TS to see the types. Neither one seems to cause any issues with typechecking the rest of your code.

However, npm does report 15 known vulnerabilities in the current dependency tree, including 1 at the highest level severity. I'd suggest at least reviewing the output of `npm audit`.

**Comment by joshuadavidson** [comment]
> I've realized that the version of TS recorded in your `package-log.json` is actually 4.7.4, so it is compatible with `blackbox-log` without any updates. You will need to either change to `"moduleResolution": "nodenext"` or add `"resolvePackageJsonExports": true` for TS to see the types. Neither one seems to cause any issues with typechecking the rest of your code.

Hmm, I'm not sure where you're seeing typescript `4.7.4`. The project's `package.json` shows `4.6.3`. In the end, I really don't see the value add in attempting a WASM blackbox log solution in an electron app as the blackbox log is bundled in. Maybe I'm missing something though. Perhaps you can comment on what it adds to the project? I think a more compelling case would be an entirely web based version. 

> However, npm does report 15 known vulnerabilities in the current dependency tree, including 1 at the highest level severity. I'd suggest at least reviewing the output of `npm audit`.

Yeah I saw these via Dependabot--they are all dev dependencies. Production dependencies have no vulnerabilities (`npm audit --omit=dev`). I'll go ahead and update what I can with the dev deps anyway though.

**Comment by joshuadavidson** [comment]
Closing for now but happy to continue discussion here.
