### ISSUE TITLE
Support RotorFlight blackbox

### ISSUE THREAD

**Issue by redjacketKR** [gimbal-ghost/gimbal-ghost#48]
Howdy!

Rotorflight, 3D RC helicopter SW based on betaflight, uses rcCommand[3] as a collective angle value with a little different scale and value. 

By modifying following line would work for RF2 bbl files. (-500~500 to 1000 to 2000) 

line 285 of "gimbal-ghost/packages/main/renderer /BlackboxFlight.ts"

            throttle: Number(logData['rcCommand[3]']),

to 

            throttle: 1500 + Number(logData['rcCommand[3]']),

Just like you made button for reverse yaw, can you make another button for RotorFlight and calcualate the modified data ?

Thank you.

**Comment by redjacketKR** [comment]
I end up modified and compiled myself. Great opportunity to learn Electron building system. 

Case closed.

**Comment by joshuadavidson** [comment]
Thanks for reaching out! I'd like to implement this and release it for the community. Do you feel comfortable doing a PR? If not, can you provide me with a sample black box file I can use to test with?

**Comment by redjacketKR** [comment]
Thanks,

I can attach a RotorFlight2 blackbox example here. I'm not dev and do not know git system. So I will write here it's nothing much. 

[#1 X38_30_20240315_201519.zip](https://github.com/gimbal-ghost/gimbal-ghost/files/14615659/1.X38_30_20240315_201519.zip)


Heli uses pitch angle(ch4) and throttle (ch5) so I change the code.
* core part for Heli RF2 bbl * in "\packages\main\renderer\BlackboxFlight.ts"
* the rest is just for convenience of oriental RC heli user. 

`            // Yaw must be inverted from the raw data
            yaw: Number(logData['rcCommand[2]']),
            throttle: 1500+Number(logData['rcCommand[3]']),`

[FrameResolver.zip](https://github.com/gimbal-ghost/gimbal-ghost/files/14615705/FrameResolver.zip)


Actually, someone asked me to make it generate trails of the stick end point.
If you can make it happen that will be great. I guess it's one of the top request also.

I have some other Ideas of linking this to simulator (accuRC) and (real Model - RF2)
That's just a thought

I was about to study git system and upload this as a name of 
'gibal ghost for rotorflight2' :-) 

Thanks!

**Comment by joshuadavidson** [comment]
Thanks for providing the blackbox file. It may take me some time to get around to implementing--so please be patient. When I have a release candidate I'll let you know and you can test it.

**Comment by redjacketKR** [comment]
Sure. Thank you.

**Comment by joshuadavidson** [comment]
@redjacketKR I have published a [release candidate](https://github.com/gimbal-ghost/gimbal-ghost/releases/tag/v1.3.0-rc.0) with the changes to support rotorflight. You'll need to select rotorflight as the blackbox source from the settings:
![image](https://github.com/gimbal-ghost/gimbal-ghost/assets/16453351/bc775ceb-c16b-4afb-b62a-e8a1e0fcce1f)

Please download, give it a try and let me know how it works for you. If everything is good, I'll publish the official release.

**Comment by redjacketKR** [comment]
Yes, as I wrote in README.md comment. I downloaded and built RC1. I tested on RF2 bbl file and it works alright! thank you for your help. 

![스크린샷 2024-03-24 234758](https://github.com/gimbal-ghost/gimbal-ghost/assets/37834299/a56c4c32-da27-4283-99a7-524ba7ed89fd)

**Comment by joshuadavidson** [comment]
Thanks for testing! I'll release today.

**Comment by redjacketKR** [comment]
I was not careful enough to look at the direction of the YAW. 
I got a note a fewdays ago and he told me it is not correct. 
Watching the yaw direction of the gimbal from above the photo shows it should be reversed, too. 

I look though your new code and it was just not a oneline fixing this time.

will you be kind enough to fix that?

Thank you

**Comment by joshuadavidson** [comment]
@redjacketKR Thanks for reporting! I have published a [release candidate](https://github.com/gimbal-ghost/gimbal-ghost/releases/tag/v1.3.1-rc.0) with the fix. Please download and verify functionality for Rotorflight. Take your time and feel free to have others test as well.

**Comment by joshuadavidson** [comment]
That's fine. Just let me know if anything is found.

**Comment by redjacketKR** [comment]
https://www.youtube.com/watch?v=0jRBu9Sbxq0

This video confirms Johny the pilot didn't have a problem.
I think it's alright to publish. :-)

**Comment by joshuadavidson** [comment]
Thanks for checking! Cool to see gimbal ghost working for helicopters! Latest fix has been included in [v1.3.1](https://github.com/gimbal-ghost/gimbal-ghost/releases/tag/v1.3.1)
